In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from IPython.display import display

In [3]:
df=pd.read_csv('text.csv')
df5=df.copy()
df5=df5.head(400000)

data0=df5.loc[df5['label']==0].head(1000)
print(data0)
data1=df5.loc[df5['label']==1].head(1000)
print(data1)
data2=df5.loc[df5['label']==2].head(1000)
print(data2)
data3=df5.loc[df5['label']==3].head(1000)
print(data3)
data4=df5.loc[df5['label']==4].head(1000)
print(data4)
data5=df5.loc[df5['label']==5].head(1000)
print(data5)
df2=pd.concat([data0,data1,data2,data3,data4,data5], axis=0)
df2

      Unnamed: 0                                               text  label
1              1  ive enjoyed being able to slouch about relax a...      0
3              3                         i dont know i feel so lost      0
5              5         i was beginning to feel quite disheartened      0
9              9  i can still lose the weight without feeling de...      0
11            11  im feeling a little like a damaged tree and th...      0
...          ...                                                ...    ...
3463        3463  i am always torn as to whether i feel sorry fo...      0
3465        3465  im feeling quite disheartened and a little ang...      0
3468        3468  i feel lost and broken but i know theres still...      0
3469        3469  i was feeling so hopeless that i messaged him ...      0
3471        3471  i feel in my heart far out weighs the horrible...      0

[1000 rows x 3 columns]
      Unnamed: 0                                               text  label
7              7  i fear that they won t ever feel that deliciou...      1
10            10  i try to be nice though so if you get a bitchy...      1
12            12  i have officially graduated im not feeling as ...      1
14            14  i feel my portfolio demonstrates how eager i a...      1
15            15  i may be more biased than the next because i h...      1
...          ...                                                ...    ...
2910        2910  when i passed the driving test after three fai...      1
2911        2911  i feel myself flourish like a precious flower ...      1
2916        2916  i used to feel all the time but its not ok wit...      1
2917        2917  i didnt feel safe in my room because the argum...      1
2919        2919  i was feeling all super duper glam in my gown ...      1

[1000 rows x 3 columns]
       Unnamed: 0                                               text  label
6               6  i would think that whomever would be lucky eno...      2
30             30  i guess that feeling is what im really getting...      2
34             34  i was less intelligent and could not really fe...      2
42             42  i think a guy can make up for lacking funds in...      2
51             51  i would want to thank them for letting my hear...      2
...           ...                                                ...    ...
12435       12435  i realized that i was simply feeling sympathet...      2
12451       12451  i have fucked a billion and one people and he ...      2
12463       12463                              i feel loyal to style      2
12465       12465  i do like any and every opportunity afforded t...      2
12467       12467                        i feel your heart loving me      2

[1000 rows x 3 columns]
      Unnamed: 0                                               text  label
13            13  i feel like a jerk because the library student...      3
17            17  i miss all the others as well that feel that i...      3
19            19  i saunter through the airport terminals feelin...      3
20            20  i need to feel dangerous and pretty so here a ...      3
28            28                                               when      3
...          ...                                                ...    ...
7240        7240  i do not want to be selfish but i feel selfish...      3
7248        7248  im saying is that every year im almost the fir...      3
7250        7250  i could feel the waves of infuriated disapprov...      3
7251        7251  i can feel my body being insulted if you will ...      3
7259        7259  i believe that just might be the most difficul...      3

[1000 rows x 3 columns]
      Unnamed: 0                                               text  label
0              0      i just feel really helpless and heavy hearted      4
2              2  i gave up my internship with the dmrg and am f...      4
4              4  i am a kindergarten teacher and i am thoroughl...      4
40            40  i dunno i just feel scared to walk in after aw...      4
47            47  i feel a bit intimidated and out of my league ...      4
...          ...                                                ...    ...
8569        8569  i am feeling extremely anxious and panicky abo...      4
8577        8577  i think most of us would feel uncomfortable ab...      4
8578        8578  i woke up feeling like my vadge was being tort...      4
8582        8582  i was feelin pretty confused and she said some...      4
8635        8635  i carry another child in a body that im now fe...      4

[1000 rows x 3 columns]
       Unnamed: 0                                               text  label
8               8  im forever taking some time out to have a lie ...      5
89             89                   i was feeling really overwhelmed      5
116           116  i really love reading bible because i can feel...      5
153           153  im feeling a bit amazed and grateful about hav...      5
157           157  i just sat there feeling this weird feeling an...      5
...           ...                                                ...    ...
27057       27057  i have this crush on my bus mate and i feel st...      5
27132       27132                  i feel weird with it straightened      5
27138       27138  i am older and my life is very different i can...      5
27169       27169  i can certainly answer as to what is my feelin...      5
27196       27196  i feel so amazed at what david rochus and rach...      5

[1000 rows x 3 columns]

       Unnamed: 0                                               text  label
1               1  ive enjoyed being able to slouch about relax a...      0
3               3                         i dont know i feel so lost      0
5               5         i was beginning to feel quite disheartened      0
9               9  i can still lose the weight without feeling de...      0
11             11  im feeling a little like a damaged tree and th...      0
...           ...                                                ...    ...
27057       27057  i have this crush on my bus mate and i feel st...      5
27132       27132                  i feel weird with it straightened      5
27138       27138  i am older and my life is very different i can...      5
27169       27169  i can certainly answer as to what is my feelin...      5
27196       27196  i feel so amazed at what david rochus and rach...      5

[6000 rows x 3 columns]

In [4]:
df2['text'] = df2['text'].str.split(' ',)
df2

       Unnamed: 0                                               text  label
1               1  [ive, enjoyed, being, able, to, slouch, about,...      0
3               3                 [i, dont, know, i, feel, so, lost]      0
5               5  [i, was, beginning, to, feel, quite, dishearte...      0
9               9  [i, can, still, lose, the, weight, without, fe...      0
11             11  [im, feeling, a, little, like, a, damaged, tre...      0
...           ...                                                ...    ...
27057       27057  [i, have, this, crush, on, my, bus, mate, and,...      5
27132       27132           [i, feel, weird, with, it, straightened]      5
27138       27138  [i, am, older, and, my, life, is, very, differ...      5
27169       27169  [i, can, certainly, answer, as, to, what, is, ...      5
27196       27196  [i, feel, so, amazed, at, what, david, rochus,...      5

[6000 rows x 3 columns]

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(lowercase=False, tokenizer=lambda x: x, preprocessor=lambda x: x)

X = vectorizer.fit_transform(df2['text'])

df_encoded = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

df_encoded
#print(df_encoded.head(6))
#print(df_encoded.tail(6))

C:\Users\cypri\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,a,aaron,aback,abandon,abandoned,abandonment,abc,abdomen,abdominal,abilities,...,ziva,zombie,zone,zoo,zoom,zooming,zouk,zss,zumba,zurich
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5998,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
#print(df_encoded.shape)
#print(df2['label'].shape)
df2 = df2.reset_index(drop=True)
df_concatenated = pd.concat([df_encoded, df2['label']], axis=1)
print(df_concatenated)
#print(df_concatenated['label'].loc[df_concatenated['label']>=5])

      a  aaron  aback  abandon  abandoned  abandonment  abc  abdomen  \
0     2      0      0        0          0            0    0        0
1     0      0      0        0          0            0    0        0
2     0      0      0        0          0            0    0        0
3     0      0      0        0          0            0    0        0
4     3      0      0        0          0            0    0        0
...  ..    ...    ...      ...        ...          ...  ...      ...
5995  0      0      0        0          0            0    0        0
5996  0      0      0        0          0            0    0        0
5997  0      0      0        0          0            0    0        0
5998  1      0      0        0          0            0    0        0
5999  0      0      0        0          0            0    0        0

      abdominal  abilities  ...  zombie  zone  zoo  zoom  zooming  zouk  zss  \
0             0          0  ...       0     0    0     0        0     0    0
1             0          0  ...       0     0    0     0        0     0    0
2             0          0  ...       0     0    0     0        0     0    0
3             0          0  ...       0     0    0     0        0     0    0
4             0          0  ...       0     0    0     0        0     0    0
...         ...        ...  ...     ...   ...  ...   ...      ...   ...  ...
5995          0          0  ...       0     0    0     0        0     0    0
5996          0          0  ...       0     0    0     0        0     0    0
5997          0          0  ...       0     0    0     0        0     0    0
5998          0          0  ...       0     0    0     0        0     0    0
5999          0          0  ...       0     0    0     0        0     0    0

      zumba  zurich  label
0         0       0      0
1         0       0      0
2         0       0      0
3         0       0      0
4         0       0      0
...     ...     ...    ...
5995      0       0      5
5996      0       0      5
5997      0       0      5
5998      0       0      5
5999      0       0      5

[6000 rows x 9069 columns]

In [12]:

import numpy as np
import tensorflow as tf
tf.__version__
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

#(train_data, train_labels), (test_data, test_labels) = df_concatenated.load_data()
#print(train_data)
#print(test_labels)

#train_labels_one_hot = to_categorical(train_labels, num_classes=6)
#test_labels_one_hot = to_categorical(test_labels, num_classes=6)

#train_data = df_encoded.head(800)
#train_labels = df2['label'].head(800)
#test_data = df_encoded[800:999]
#test_labels = df2['label'][800:999]

#train_data_np = train_data.to_numpy().astype('float32')
#train_labels_np = to_categorical(train_labels.to_numpy())
#train_labels_np = tf.keras.utils.to_categorical(train_labels_np, num_classes=6)
#test_data_np = test_data.to_numpy().astype('float32')
#test_labels_np = to_categorical(test_labels.to_numpy())
#test_labels_np = tf.keras.utils.to_categorical(test_labels_np, num_classes=6)

#X_test = df_concatenated.head(4800).iloc[:, :-1].values
#y_test = df_concatenated.head(4800).iloc[:, -1].values

X_test = df_concatenated[:4800].iloc[:, :-1].values
y_test = df_concatenated[:4800].iloc[:, -1].values

X_train = df_concatenated[4800:].iloc[:, :-1].values
y_train = df_concatenated[4800:].iloc[:, -1].values

y_train_one_hot = to_categorical(y_train,num_classes=6)
y_test_one_hot = to_categorical(y_test,num_classes=6)

#print(X_test[-1].shape)


model = Sequential([
    Flatten(),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'), 
    Dense(6, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train_one_hot, epochs=5, batch_size=32)


test_loss, test_acc = model.evaluate(X_test, y_test_one_hot, batch_size=32)

print(f'Test accuracy: {test_acc}')

Epoch 1/5
38/38 [==============================] - 2s 22ms/step - loss: 1.0197 - accuracy: 0.7925
Epoch 2/5
38/38 [==============================] - 1s 22ms/step - loss: 0.4124 - accuracy: 0.8333
Epoch 3/5
38/38 [==============================] - 1s 22ms/step - loss: 0.1918 - accuracy: 0.9333
Epoch 4/5
38/38 [==============================] - 1s 26ms/step - loss: 0.0686 - accuracy: 0.9842
Epoch 5/5
38/38 [==============================] - 1s 25ms/step - loss: 0.0318 - accuracy: 0.9925
150/150 [==============================] - 1s 6ms/step - loss: 9.0398 - accuracy: 0.0835
Test accuracy: 0.08354166895151138

In [8]:
model.save('modele_trained2.keras')

In [9]:
from tensorflow.keras.models import load_model
modele_charge = load_model('modele_trained2.keras')

In [10]:
#df3=df.copy().head(1000)

#def transf_en_hot(texte):
    #texte_sep=[texte.split(' ',)]
    #print(texte_sep)
    #texte_df = pd.DataFrame([texte_sep])
    #print(texte_df)
    #df3=df.copy().head(1000)
    #df3['text'] = df3['text'].str.split(' ',)
    #df_total=pd.concat([df3['text'], texte_df], axis=0)
    #print(df_total)
    #df_total_vect = vectorizer.fit_transform(df_total[0])
    #print(df_total_vect)
    #df_total_encoded = pd.DataFrame(df_total_vect.toarray(), columns=vectorizer.get_feature_names_out())
    #print(df_total_encoded)
    #return(df_total_encoded.iloc[-1].values)

def transf(texte,vectorizer):
    texte_preprocessed = [texte]  # Appliquez votre logique de tokenisation/prétraitement si nécessaire
    texte_vect = vectorizer.transform(texte_preprocessed)
    return texte_vect.toarray()

In [11]:
prediction = modele_charge.predict(transf('i just feel so angered sometimes',vectorizer))
print(prediction)
classe_predite = np.argmax(prediction, axis=1)
print(classe_predite)

1/1 [==============================] - 0s 238ms/step
[[5.2400159e-05 4.9852930e-05 3.1578460e-05 1.7666076e-04 1.6283646e-02
  9.8340595e-01]]
[5]